apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: default
  name: dev-app
spec:
  # http:
  #   service:
  #     spec:
  #       type: ClusterIP
  version: 8.14.1
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: elasticsearch-quickstart
        namespace: default
    # logs:
    #   elasticsearchRefs:
    #   - name: monitoring
    #     namespace: observability  
  nodeSets:
  - name: all-roles
    count: 1
    config:
      node.roles: [ master, data, ingest, transform, remote_cluster_client ]
    podTemplate:
      metadata:
        annotations:
          # optional / recommended: disabling self-collecting logs
          co.elastic.logs/enabled: "false"
      spec:
        # tolerations:
        #   - key: "area"
        #     operator: "Equal"
        #     value: "monitoring"
        #     effect: "NoSchedule"
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        # containers:
        # - name: elasticsearch
        #   resources:
        #     requests:
        #       memory: 4Gi
        #       cpu: 1
        #     limits:
        #       memory: 4Gi
        #       cpu: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
#        storageClassName: default