apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: monitoring
  name: stack-monitoring
spec:
  # http:
  #   service:
  #     spec:
  #       type: ClusterIP
  version: 8.14.1
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: stack-monitoring
        namespace: monitoring
    logs:
      elasticsearchRefs:
      - name: stack-monitoring
        namespace: monitoring
  nodeSets:
  - name: all-roles
    count: 3
    config:
      node.roles: [ master, data, ingest, transform, remote_cluster_client ]
    podTemplate:
      spec:
        # tolerations:
        #   - key: "area"
        #     operator: "Equal"
        #     value: "monitoring"
        #     effect: "NoSchedule"
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        # containers:
        # - name: elasticsearch
        #   resources:
        #     requests:
        #       memory: 4Gi
        #       cpu: 1
        #     limits:
        #       memory: 4Gi
        #       cpu: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  namespace: monitoring
  name: stack-monitoring
spec:
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: stack-monitoring
        namespace: monitoring
    logs:
      elasticsearchRefs:
      - name: stack-monitoring
        namespace: monitoring
  # config:
  #   server.publicBaseUrl: "https://custom-fqdn.example.com"
  http:
    service:
      spec:
        type: LoadBalancer
        #externalTrafficPolicy: Local
  version: 8.14.1
  count: 1
  elasticsearchRef:
    name: stack-monitoring
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 400Mi
            cpu: 300m
          limits:
            memory: 2Gi
            cpu: 2
