apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    app: mysql
---
# Mysql Deployment
# Deployment de la imagen eedugon/flask-counter-mysql:v0.1
# no tiene persistencia
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  name: mysql-sts
spec:
  serviceName: "mysql-headless"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: datos-mysql
        - name: init-volume
          mountPath: /docker-entrypoint-initdb.d
        env:
          - name: MYSQL_DATABASE
            value: "contador-db"
          - name: MYSQL_USER
            value: "flaskuser"
          - name: MYSQL_PASSWORD
            value: "patodegoma"
          - name: MYSQL_ROOT_PASSWORD
            value: "root1234"
      volumes:
        - name: init-volume
          configMap:
            name: init-configmap
  volumeClaimTemplates:
  - metadata:
      name: datos-mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 2Gi
